server:
  port: 8100

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kmail?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wl.kmail.model

logging:
  level:
    com.wl.kmail: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql